#config_version=6
hardware:
  platform: fast
  driverboards: fast

fast:
  net:
    controller: neuron
    io_loop:
      cab:
        model: FP-I/O-0024-3
        order: 1
      "0804":
        model: FP-I/O-0804-3
        order: 2
      1616:
        model: FP-I/O-1616-3
        order: 3
      3208:
        model: FP-I/O-3208-2
        order: 4
    port: auto
    baud: 921600
    debug: false
    watchdog: 1s
    default_quick_debounce_open: 2ms
    default_quick_debounce_close: 2ms
    default_normal_debounce_open: 4ms
    default_normal_debounce_close: 4ms
  exp:
    boards:
      exp_2000:
        model: FP-EXP-2000
        led_fade_time: 100ms
      exp_91:
        model: FP-EXP-0091
        led_fade_time: 100ms
    port: auto
    baud: 921600
    debug: false



switches:
  s_left_flipper:
    number: 0B
    tags: left_flipper
  s_left_upper_flipper:
    number: 0C
    tags: left_flipper
  s_right_flipper:
    number: 10
    tags: right_flipper

coils:
  c_flipper_left_main:
    number: 0D
  c_flipper_left_hold:
    number: 0C
    allow_enable: true
  c_flipper_right_main:
    number: 0F
  c_flipper_right_hold:
    number: 0E
    allow_enable: true
  c_flipper_upper_left_main:
    number: 23
  c_flipper_upper_left_hold:
    number: 22
    allow_enable: true

playfields:
  playfield:
    tags: default
    default_source_device: None  # use None in steps before 8

flippers:
  left_flipper:
    main_coil: c_flipper_left_main
    hold_coil: c_flipper_left_hold
    activation_switch: s_left_flipper
    enable_events: machine_reset_phase_3
  right_flipper:
    main_coil: c_flipper_right_main
    hold_coil: c_flipper_right_hold
    activation_switch: s_right_flipper
    enable_events: machine_reset_phase_3
  left_upper_flipper:
    main_coil: c_flipper_upper_left_main
    hold_coil: c_flipper_upper_left_hold
    activation_switch: s_left_upper_flipper
    enable_events: machine_reset_phase_3